---
mal_types:
  - name: bash
    shell: bash {}
  - name: python
    shell: python {}
  - name: python3
    shell: python3 {}
  - name: elf
    shell: ./{}
  - name: ruby
    shell: ruby {}
